# Subsequence of a string is a new string generated by deleting zero or more characters from the original without changing the order if the remaining characters

def is_subsequence(string, sub):
    iterable = iter(string)
    return all(i in iterable for i in sub)

original = input("Enter the original string: ")
sub = input("Enter a string to check: ")

if is_subsequence(original, sub):
    print(f"{sub} is a subsequence of {original}")
else:
    print(f"{sub} is not a subsequence of {original}")

# name = "Dennis"

# for i in name:
#     print(i)

# iterable = iter(name)

# for i in iterable:
#     print(i)